import 'package:flutter/material.dart';
const activeCardColour = Color(0xFF1D1E33);
const inactiveCardColour = Color(0xFF111328);
const selectedCardColor=Color(0xFFEB1555);
const bottomCardColour = Color(0xFFEB1555);
const bottomCardHeight = 80.0;
const labelTextStyle= TextStyle(fontSize: 18.0,color:Color(0xFF8D8E98));
const numberTextStyle=TextStyle(fontSize: 50.0,fontWeight: FontWeight.w900);
const resultTextStyle=TextStyle(fontSize: 22.0,color: Color(0xFF24D876), fontWeight: FontWeight.bold);
const bmiTextStyle=TextStyle(fontSize: 100.0, fontWeight: FontWeight.bold);